<?php

namespace app\controllers;

use Yii;
use app\models\Result;
use app\models\ResultSearch;
use app\models\ReportSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;

/**
 * ResultController implements the CRUD actions for Result model.
 */
class ResultController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Result models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReportSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAddResult()
    {
      $model = new Result();
      if ($model->load(Yii::$app->request->post())) {
          $success = false;
          $error = [];
          if($model->save())    {
              $success = true;
          }   else    {
              $error = $model->getErrors();       //get validation error messages
          }
          header('Cache-Control: no-cache, must-revalidate');
          header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
          header('Content-type: application/json');
          echo json_encode(['success' => $success, 'error' => $error ]);

          Yii::$app->end();
      } else {
          return $this->render('contact', [
              'model' => $model,
          ]);
      }
    }

    public function actionViewReport($id) {
      return $this->render('/report/viewPrint', [
          'id' => $id,
      ]);
    }

    public function actionDownloadReport($id) {
      $pdf = new Pdf([
          'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
          'content' => $this->renderPartial('/report/viewPrint', ['id'=>$id]),
          'destination' => Pdf::DEST_DOWNLOAD,
          'options' => [
              'title' => 'Results Report - Pathology Lab Reporting System',
              'subject' => 'Your Report'
          ],
          'methods' => [
              'SetHeader' => ['Generated By: Pathology Lab Reporting System||Generated On: ' . date("r")],
              'SetFooter' => ['|Page {PAGENO}|'],
          ]
      ]);
      //var_dump("cheguei!");die();
      return $pdf->render();
    }

    public function actionEmailReport($id) {
      if(Yii::$app->mailer->compose()
          ->setFrom('evertonmj@gmail.com')
          ->setTo('evertonmj@gmail.com')
          ->setSubject('Here\'s your report from Pathology Lab')
          ->setHtmlBody('<b>Here\'s your report!</b>')
          ->send()) {
        return "foi!";
      } else {
        return "nao foi!";
      }

    }

    /**
     * Finds the Result model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Result the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Result::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
